var Text={
		nil:"无",
		infinite:"无限",
		back:"是否返回？",
		dropHandCardOver:"手牌弃置完毕",
		pleaseClickNextButton:"请点击下一阶段",
		skillShow:"{0}\n{1}",
		baofa:"(爆发)",
		askBaofaGoumang:"是否爆发“句芒”？",
		askBaofaFeifei:"是否爆发肥肥？",
		askBaofaTayunxue:"是否爆发【踏云靴】免疫本次伤害？",
		askDiandang:"是否发动“典当”效果？",
		baofaFeifeiEffect:"{0}爆发肥肥，本方战力+3",
		changeCardFromDeck:"{0}从牌堆中交换了手牌",
		player1ExchangeCardWithPlayer2:"{0}与{1}手牌对调",
		showSkill:"【{0}】\n{1}\n【{2}】\n{3}\n",
		showPlayerSelectedCharacter:"玩家{0}选择了{1}",
		friendChooseCharacter:"您的队友选择了{0}\n请您选择角色",
		chooseExtractCard:"请选择要抽取的牌",
		extractArm:"{0}抽取{1}一件武器:{2}",
		extractDefense:"{0}抽取{1}一件防具:{2}",
		extractOrnament:"{0}抽取{1}一件饰品",
		extractHandCard:"{0}抽取{1}一张手牌",
		chooseDropCard:"请选择弃掉的牌",
		chooseDropHandCard:"请选择弃置的手牌",
		chooseDropEqument:"请选择丢弃的装备",
		chooseDropOrnament:"请选择丢弃的饰品",
		chooseNpcEffect:"{0}选择NPC助战效果",
		choosePlayerAddHandCard:"请选择一人补{0}张牌",
		choosePlayerGiveCardToFriend:"请指定一名玩家将1张手牌交给队友",
		choosePlayerReduceHP:"请指定一名玩家损失{0}点HP",
		chooseCardGiveToFriend:"请选择一张牌交给队友",
		chooseGiveTarget:"请选择交予的目标",
		chooseAddCardTarget:"请指定一人补{0}张牌",
		chooseAddHpTarget:"请指定一名角色HP+{0}",
		choosePlayerDropCard:"请选择一名玩家弃掉1张手牌",
		choosePlayerGivePetToFriend:"请选择一名角色将其宠物交给队友",
		choosePetGiveToFriend:"请选择交给队友的宠物",
		choosePlayerDropAllCard:"请选择一名角色弃掉全部手牌",
		chooseReplacePlayer:"请选择替换的角色",
		chooseHandCardGiveBoss:"请选择1张手牌交给魔主",
		chooseIsFighting:"是否打怪？",
		chooseUseJinchanguimu:"是否使用金蟾鬼母进行{0}？",
		chooseNpcEffect:"请选择要执行的NPC效果",
		chooseUseFightCardOrClickNextButton:"请选择要出的战牌或进入下一阶段",
		chooseIsHunzhan:"是否混战？",
		chooseUseNPCHelpeCardNumber:"请选择要使用的NPC牌数量",
		chooseAwardCharacter:"请选择第{0}名备选角色（共2名）",
		chooseGuanyinmizhen:"请选择放置【观音迷阵】的角色（该角色跳过下一个补牌阶段）",
		chooseHuayaoshuiPet:"请选择一名角色，消灭其1只宠物(还需消灭共计至少{0}点战力的宠物)",
		chooseJushentiantuEffect:"请按先后顺序选择要执行其失败效果的宠物(未选择的宠物将会被丢弃)",
		choosePlayerAdditionalReduceHp:"请选择一人HP额外-2",
		chooseAdditionalAwardCharacter:"请额外选择第1名备选角色",
		advChoosePlayerRole:"请选择{0}号玩家的角色",
		askIsAddTriggerCombat:"是否为触发方增加战力？(否则为怪物方增加)",
		npcHelperEffectAddTriggerCombat:"{0}使用NPC助战效果，为触发方增加{1}点战力",
		npcHelperEffectAddMonsterCombat:"{0}使用NPC助战效果，为怪物方增加{1}点战力",
		dropArm:"{0}弃掉武器:{1}",
		dropDefense:"{0}弃掉防具:{1}",
		dropOrnament:"{0}弃掉饰品:{1}",
		dropCard:"{0}弃置【{1}】",
		dropPet:"{0}弃置了宠物：{1}",
		getTreasure:"获得仙宝【{0}】",
		allPlayerHaveNoEqumentToDrop:"场上角色无装备可弃",
		haveNoEqumentToDrop:"{0}无装备可弃",
		support:"支援",
		hinder:"妨碍",
		asSupporter:"{0}作为支援者",
		asHinder:"{0}作为妨碍者",
		hinderHaveNoEquipmentAndHandCard:"妨碍者无装备和手牌",
		noSupporter:"无支援者",
		takeOverMonster:"翻取怪物牌:{0}",
		monsterDeckIsNull:"怪物牌堆已空，无法翻取下一张",
		takeOverNextMonster:"{0}翻取下一张怪牌",
		playerChooseNotFight:"{0}选择不打怪",
		bossDice:"魔主骰子点数为：{0}，怪物战力+{1}",
		giveCardToFriend:"{0}将1张手牌交给队友{1}",
		giveCardError:"队友已阵亡，无法将手牌交予队友",
		loverAddCombat:"由于倾慕效果，NPC战力×2",
		triggerFinalCombat:"触发方最终战力:{0}",
		monsterFinalCombat:"怪物方最终战力:{0}",
		battleWin:"打怪胜利",
		battleLose:"打怪失败",
		mineChooseResult:"您选择了{0}",
		perishPet:"{0}消灭了{1}的宠物{2}",
		petFeng:"风系宠物",
		petLei:"雷系宠物",
		petShui:"水系宠物",
		petHuo:"火系宠物",
		petTu:"土系宠物",
		effectCanNotEffectedJinchanguimu:"{0}效果对金蟾鬼母无效",
		monsterMsgShow:"{0}\n战力:{1}\n闪避:{2}\n宠物效果:{3}\n\n出场效果:{4}\n\n胜利结算:{5}\n\n失败结算:{6}",
		npcMsgShow:"{0}\n战力:{1}\nNPC效果1:{2}\nNPC效果2:{3}",
		handCardDeck:"牌堆：{0}",
		monsterDeck:"怪物：{0}",
		dropDeck:"弃牌：{0}",
		playerUsedCard:"{0}打出了【{1}】",
		playerEquipCard:"{0}装备了【{1}】",
		addHandCard:"{0}从牌堆中补了{1}张牌",
		diandangMojian:"{0}典当【魔剑】，从牌堆中补了2张牌",
		longhunzhankaiEffet:"由于【龙魂战铠】效果，抵御1点伤害",
		tayunxueEffect:"{0}爆发【踏云靴】免疫本次伤害，并恢复1点HP",
		qiankundaopaoEffect:"{0}由于【乾坤道袍】效果，免疫技牌导致的伤害",
		shiziyaoshuoEffect:"【十字妖槊】效果触发，本方战力+1",
		tiangangdouyiEffect:"【天罡斗衣】进入您的装备区，您的HP回满",
		reduceHp:"{0}HP-{1}",
		addHp:"{0}HP+{1}",
		addCombat:"{0}战力+{1}",
		natureFeng:"风",
		natureLei:"雷",
		natureShui:"水",
		natureHuo:"火",
		natureTu:"土",
		crisis:"危机",
		npcChuangongEffect:"您补1张牌",
		npcXiulianEffect:"您损失1点HP后指定任意一人补1张牌",
		npcDaoqieEffect:"您弃掉任意玩家的1张手牌",
		daoqieError:"场上无人有手牌，盗窃效果无效",
		xunhuaError1:"队友已阵亡，驯化效果无效",
		xunhuaError2:"场上无人有宠物，驯化效果无效",
		yaowangEffect:"柳梦璃“妖王”效果触发，所在阵营的每个宠物额外获得“主人战力+1”的宠物效果",
		tianxuanwuyinDesc:"【天玄五音】您指定一方本场战斗中战力+2未参战亦可使用",
		jincanwangDesc:"【金蚕王】本场战斗中您的战力+3参战并命中才会生效",
		dongmingbaojingDesc:"【洞冥宝镜】任意玩家决定是否翻取怪物牌前使用，指定一名玩家翻取怪物牌堆顶上的一张，检视后放回原处",
		yinguDesc:"【隐蛊】抵消一次您自己收到的HP伤害（倾慕除外）",
		shuerguoDesc:"【鼠儿果】您指定一人补2张手牌",
		linghuxiandanDesc:"【灵葫仙丹】您的技牌阶段使用，您自己的HP+2当有玩家HP为0时，可令其复活并恢复2点HP",
		bingxinjueDesc:"【冰心诀】任意玩家使用技牌、战牌、特殊牌时打出。可令当前打出的这张牌无效",
		tongqianbiaoDesc:"【铜钱镖】弃掉任意玩家的1张手牌或装备",
		tianleipoDesc:"【天雷破】您指定一名玩家HP-2(此伤害为雷属性)",
		tiangangzhanqiDesc:"【天罡战气】本场战斗中您的战力（含装备、宠物）加倍。但对战牌、爆发等临时增加的战力无效参战并命中才会生效",
		jinchantuoqiaoDesc:"【金蝉脱壳】强制结束本场战斗，胜利条件、失败条件皆无效参战者可使用，即使未命中",
		kuicetianjiDesc:"【窥测天机】您从怪物牌组顶端翻去两张怪牌，检视后放回原位允许改变二者之间的顺序",
		toudaoDesc:"【偷盗】您抽取任意玩家的1张手牌",
		wuqichaoyuanDesc:"【五气朝元】我方全体HP+1;典当:您的技牌阶段，可以弃掉此牌，补1张牌",
		mojianDesc:"【魔剑】命中+1;典当：您的技牌阶段，可以放弃【魔剑】（是否装备均可），之后您补2张牌",
		caihuanDesc:"【彩环】命中+2",
		modaotianzhaDesc:"【魔刀天吒】战力+2",
		tianshezhangDesc:"【天蛇杖】战力+1 装备【天蛇杖】的角色,如果HP得到回复(倾慕除外),HP回复额外+1",
		wuchenjianDesc:"【无尘剑】战力+1，命中+1",
		tiandijifuDesc:"【天帝祭服】装备后，您可将任意手牌当作【隐蛊】使用",
		qiankundaopaoDesc:"【乾坤道袍】战力+1；装备后，您免疫技牌导致的HP伤害",
		wucaixiayiDesc:"【五彩霞衣】战力+1爆发：装备后，您HP为0时，可丢弃【五彩霞衣】复活并恢复2点HP",
		tayunxueDesc:"【踏云靴】命中+1爆发：装备后收到伤害时（倾慕除外）,您可丢弃【踏云靴】免疫本次伤害，并令HP回复1点",
		longhunzhankaiDesc:"【龙魂战铠】装备后，您受到任何伤害（倾慕除外），HP损失降低1点，最低可降至0",
		soubaoshuDesc:"【搜宝鼠】您从手牌堆上方翻取5张牌，拿取其中的3张并任意分配。其余2张弃掉",
		jimushuiDesc:"【极目水】您从怪物牌堆上方翻取3张牌，检视后弃掉其中的0～3张，其余放回怪物牌堆上方.可任意改变它们之间的顺序",
		tianjianDesc:"【天剑】您指定一名角色HP-4",
		jiushenDesc:"【酒神】您指定一方，本场战斗中战力+5.未参战亦可使用",
		xiukoujinxinzhouDesc:"【绣口锦心咒】本场战斗未触发混战时使用.您从怪物牌弃牌堆中选择1张怪物牌或NPC牌，用其触发混战.未参战亦可使用",
		kaoyaDesc:"【烤鸭】您扣除自己的n点HP，本场战斗中您的战力增加，增加量=n*2.使用此牌后您至少要保留1点HP.本牌导致的伤害隐蛊、踏云靴无效",
		wulingjingxieDesc:"【五灵净邪】当魔主翻开手牌后打出，本次魔主全部手牌无效",
		tianxiangxumingluDesc:"【天香续命露】您的技牌阶段使用，指定一人HP+5.当有玩家HP为0时使用，可令其复活并恢复5点HP",
		huanmeihuazhouDesc:"【幻魅画轴】当有危机牌被翻出后打出，可令本张危机牌无效.之后，您从手牌弃牌堆中选择1张牌，加入您的手牌.\n技牌阶段打出，可弃掉一张场内的危机牌。之后，您从手牌弃牌堆中选择1张牌，加入您的手牌",
		shiziyaoshuoDesc:"【十字妖槊】战力+1\n当您参战时，我方战力额外+2",
		tiangangdouyiDesc:"【天罡斗衣】战力+1 命中+1\n此装备进入您的装备区时，您的HP回复到满值",
		xiejianxianPetEffect:"由于邪剑仙宠物效果,{0}武器类装备扣置，能力、数值均无效",
		
		tiangangzhanqiUsing:"{0}使用【天罡战气】，自身战力加倍",
		
		
		bossUseTianxuanwuyin:"{0}使用【天玄五音】，怪物战力+2",
		bossUseJincanwang:"{0}使用【金蚕王】，魔主战力+3",
		
		bossUseJinchantuoqiao:"{0}翻出【金蝉脱壳】，强制结束本场战斗",
		
		cardNotEffect:"{0}效果无效",
		
		playerStatusRecovery:"{0}从横置状态中恢复",
		playerStatusTransverse:"{0}被横置",
		playerStatusTransverseInvaild:"{0}已经被横置，本次横置无效",
		
		stepRoundStart:"{0}的回合开始",
		
		stepSkillCardStart:"{0}的技牌阶段",
		stepHandCardEnd:"{0}的技牌阶段结束",
		
		stepFightMonsterStart:"{0}的战斗阶段",
		takeOverAndDropMonster:"翻取怪物牌【{0}】弃置",
		notUseFightCard:"{0}不使用战牌",
		stepFightMonster2Start:"{0}发动混战",
		stepFightMonsterEnd:"{0}的打怪阶段结束",
		stepAddHandCardStart:"{0}的补牌阶段",
		stepAddHandCardCountAddNumber:"{0}有{1}张牌，需要从牌堆中补{2}张牌",
		stepDropHandCardStart:"{0}的弃牌阶段",
		countShouldDropHandCardNumber:"需要弃置{0}张手牌",
		notNeedDropHandCard:"{0}不用弃牌",
		stepRoundEnd:"{0}的回合结束",
		
		skillBaiyuejiaozhuZhaohuanshuimoshouUsing:"{0}舍弃2张手牌发动“召唤水魔兽”效果",
		skillBaiyuejiaozhuZhaohuanshuimoshouEffectText:"本场战斗中，我方战力+5",
		
		skillShenqishuangYuanlingguixinshuUsing:"{0}舍弃1张技牌发动“元灵归心术”",
		
		skillTangxuejianLianjiUsing:"{0}发动“连击”效果",
		skillTangxuejianLianjiEffectText:"{0}本场战斗战力+2",
		
		skillTangxuejianHaoshengUsing:"{0}发动“好胜”，扣减自己2点HP后补2张牌",
		
		skillWangpengxuTaotieUsing:"{0}发动“饕餮”,舍弃【{1}】，自身HP+2 ",
		
		skillWangpengxuHechengshipinUsing:"{0}发动“合成饰品”，自身战力+1",
		
		skillHanlinshaJiefujipinUsing:"{0}发动“劫富济贫”，补了1张手牌",
		
		skillHanlinshaSounangtanbaoUsing:"{0}发动“搜囊探宝”效果",
		skillHanlinshaSounangtanbaoTongqianbiao:"将【{0}】当作【铜钱镖】使用",
		skillHanlinshaSounangtanbaoToudao:"将【{0}】当作【偷盗】使用",
		
		skillJiujianxianZuixianwangyuebuAddHandCard:"酒剑仙由于【醉仙望月步】效果，多补1张牌",
		
		bossForceTakeOverHandCard:"魔主手牌大于等于7张，需强制全部翻开并执行",
		bossGetMonster:"魔主获得怪物{0}",
		bossAddHandCard:"魔主{0}补了{1}张牌",
		bossTakeOverCard:"{0}翻出了【{1}】",
		bossForceHunzhan:"{0}翻出了【{1}】,本场战斗强制混战",
		bossTakeOverXianbao:"{0}翻出了【{1}】,魔主无法使用成长牌/仙宝，此牌弃置",
		
		
		bossSkillSheyaonan:"玩家在弃牌阶段手牌上限为1，可被玩家相关技能如【剑匣】覆盖.死亡退场后，替换为狐妖女",
		bossSkillHuyaonv:"魔主投掷战力骰子时，1、2、3点分别视为4、5、6点",
		bossSkillCaiyi:"玩家每受到1点伤害，魔主回复1点HP",
		bossSkillZhenyumingwang:"本局游戏中所有怪物额外获得“消灭触发者同属性宠物”的出场效果",
		bossSkillBaiyuejiaozhu:"本局游戏所有怪物胜利结算、失败结算对调\n玩家战斗失败时，本场战斗的怪物置于魔主旁，每放置1张，魔主战力永久+2，上限5张",
		bossSkillHuangshansanguai:"魔主补牌时，每次补2张",
		bossSkillXueshouduying:"玩家使用技牌、战牌、特殊牌时，必须额外弃掉1张手牌",
		bossSkillShushanqishen:"魔主在战斗时，不会投掷战力骰子\n\n魔主补牌时，每次补3张。战牌阶段，只须翻开并执行1张魔主手牌。每翻开执行1张魔主手牌后，您可决定是否再翻1张" +
		"\n\n战牌阶段，若魔主手牌大于等于7张，则强制全部依次翻开并执行",
		bossSkillJiangshili:"玩家方每获得1个宠物，魔主战力永久+1",
		bossSkillMoyiYanshiqiongbing:"本局玩家不可放弃战斗\n\n" +
		"玩家战斗失败时，本场战斗的怪物置于魔主旁，游戏结束时计算总战力，成为魔主的分数\n\n" +
		"玩家方拥有5个或以上宠物时，魔主战力永久变成10",
		bossSkillMoyiYanshiqiongbing:"魔主技能触发，本局不可放弃战斗",
		bossSkillBaiyuejiaozhu:"魔主获得第6只怪物，挑战失败",
		
		guanyinmizhenEffectText:"您将此牌放置于队伍中任意角色边。该角色的下一个补牌阶段跳过，并移除此牌",
		huayaoshuiEffectText:"我方若干宠物被消灭，被消灭的宠物总战力至少为8",
		huayaoshuiEffect2Text:"战斗结束阶段，消灭触发者战力最高的宠物",
		jushentiantuEffectText:"每名角色依次执行自身所有宠物的失败结算，或放弃该宠物",
		jushentiantuEffect2Text:"本场战斗结束后，每名角色依次执行自身所有宠物的失败结算，或放弃该宠物",
		lingquanEffectText:"将此牌放置于魔主旁，每放置1张，魔主战力永久+2",
		lingquanEffect2Text:"本场战斗魔主额外投掷1次战力骰子，怪物战力再次增加骰子点数的值",
		muhoudeyinmouEffectText:"魔主立刻补3张牌",
		muhoudeyinmouEffect2Text:"本场战斗强制失败，且无法用金蝉脱壳中止",
		tantadeqiongdingEffectText:"下次战斗中，执行本危机牌的混战效果",
		tantadeqiongdingEffect2Text:"本次战斗结算中若有对我方的HP伤害，则伤害值均为12",
		xingfengxueyuEffectText:"我方全体HP-2",
		xingfengxueyuEffect2Text:"我方所有参战者HP-4",
		
		crisisCardHuayaoshuiUsing:"【化妖水】效果发动，消灭{0}战力最高的宠物：{1}",
		crisisCardGuanyinmizhenUsing:"由于【观音迷阵】效果，{0}跳过本次补牌阶段",
		
		
		petLevelWeak:"弱",
		petLevelStrong:"强",
		petLevelBoss:"BOSS",
		monsterNoOpenEffect:"无出场效果",
		activeMonsterOpenEffect:"{0}出场效果:{1}",
		monsterOpenEffectInvalid:"{0}出场效果无效",
		monsterWinEffectInvalid:"{0}胜利结算无效",
		monsterLoseEffectInvalid:"{0}失败结算无效",
		activeMonsterWinEffect:"打怪成功触发{0}胜利结算:\n{1}",
		activeMonsterLoseEffect:"打怪失败触发{0}失败结算:\n{1}",
		activeMonsterBossBaiyuejiaozhuWinEffect:"打怪成功，由于拜月教主效果，触发失败结算:\n{0}",
		activeMonsterBossBaiyuejiaozhuLoseEffect:"打怪失败，由于拜月教主效果，触发胜利结算:\n{0}",
		
		
		yelingWinEffectText:"您补一张牌",
		yelingLoseEffectText:"您的HP-2",
		
		anxiangWinEffectText:"您的HP+2",
		anxiangLoseEffectText:"敌方全体HP+2",
		anxiangPetEffectText:"主人战力+1",
		
		diejingWinEffectText:"敌方一人HP+2（敌方任选）",
		diejingPetEffectText:"（爆发）任意角色HP降到0时，您可放弃蝶精，令其满HP复活",
		
		goumangWinEffectText:"您与支援者HP各+2",
		goumangLoseEffectText:"我方全体从牌堆中交换全部手牌，之后各自HP-2",
		goumangPetEffectText:"（爆发）我方技牌阶段或任意战斗的战牌阶段，您可放弃句芒，之后我方全体从牌堆中交换全部手牌",
		
		jiliangyinzheWinEffectText:"您指定一名玩家HP+2",
		jiliangyinzheLoseEffectText:"您的HP-3",
		
		duniangziWinEffectText:"您可以放弃若干张手牌或装备，每放弃1张，您的HP+2",
		duniangziLoseEffectText:"您损失1个装备，之后场上装备最多的角色各损失1个装备",
		duniangziPetEffectText:"主人命中+2",
		duniangziWinEffectHanleEnd:"毒娘子胜利结算处理完毕",
		duniangziWinEffectCancel:"{0}放弃执行效果",
		
		xiejianxianWinEffectText:"我方全体玩家各补n张牌，n=补牌者当前的装备数",
		xiejianxianLoseEffectText:"我方全体HP-2",
		xiejianxianPetEffectText:"敌方全体的武器类装备扣置，能力、数值无效",
		xiejianxianPetEffectRelieve:"邪剑仙效果解除，敌方所有武器类装备恢复",
		
		qianbeibuzuiOpenEffectText:"您和一名妨碍者手牌对调",
		qianbeibuzuiLoseEffectText:"您的角色横置",
		qianbeibuzuiPetEffectText:"主人战力+1",
		
		wudushouWinEffectText:"敌方全体HP-1后，您指定一人HP额外-2",
		wudushouLoseEffectText:"您的HP-2，然后失去1件装备（自选）",
		wudushouPetEffectText:"五毒兽本体战力变为8（比赛结束统计双方宠物战力时有效）",
		
		sheyaonanWinEffectText:"妨碍者HP-4",
		sheyaonanLoseEffectText:"您的HP-4",
		
		shuimoshouWinEffectText:"敌人全体HP-1，之后您抽取妨碍者1件装备或手牌",
		shuimoshouLoseEffectText:"您的HP-2，之后妨碍者抽取您的1件装备或手牌",
		shuimoshouPetEffectText:"主人战力+1，命中+1",
		
		yanyueWinEffectText:"妨害者HP-2",
		yanyueLoseEffectText:"您的HP-3",
		yanyuePetEffectText:"主人战力+1",
		
		feifeiWinEffectText:"妨害者HP-3",
		feifeiLoseEffectText:"您的HP-3",
		feifeiPetEffectText:"（爆发）任何打怪战中使用，本场战斗本方战力+3，战斗结束后放弃肥肥",
		
		huyaonvOpenEffectText:"支援者受到伤害，伤害=您的战力-1",
		huyaonvWinEffectText:"妨害者HP-3",
		huyaonvLoseEffectText:"由敌方指定两名角色HP-3",
		huyaonvPetEffectText:"主人战力+2",
		
		rongyanshouwangOpenEffectText:"全体角色HP-2",
		rongyanshouwangWinEffectText:"敌方全体HP-2",
		rongyanshouwangLoseEffectText:"您与支援者HP各-2",
		rongyanshouwangPetEffectText:"主人战力+2",
		
		chiguiwangOpenEffectText:"支援者在本场战斗中战力+2",
		chiguiwangWinEffectText:"您指定任意一名玩家补2张牌",
		chiguiwangLoseEffectText:"您的HP-2，失去全部装备并补充失去装备数量的手牌",
		chiguiwangPetEffectText:"主人在补牌阶段可多补1张牌",
		chiguiwangLoseEffectUsing:"{0}失去了全部共{1}件装备，并补充了{2}张手牌",
		
		jinchanguimuOpenEffectText:"金蟾鬼母本场战斗中战力额外+3",
		jinchanguimuWinEffectText:"敌方全体HP-1",
		jinchanguimuLoseEffectText:"我方HP-2",
		jinchanguimuPetEffectText:"任何战斗，允许选择金蟾鬼母进行支援，妨碍（战力4，命中4，HP不会增减）",
		
		petChiguiwangEffectUsing:"由于赤鬼王宠物效果{0}多补1张牌",
		
		
		xingtianOpenEffectText:"参战者以外的所有角色HP-n，n=持有该角色玩家的手牌数",
		xingtianPetEffectText:"主人命中+1",
		
		xuanguiWinEffectText:"您与支援者HP各-3",
		xuanguiLoseEffectText:"妨碍者HP-3",
		
		tianguihuangLoseEffectText:"如果敌方有土属性宠物，可以选择用天鬼皇替换该宠物",
		tianguihuangPetEffectText:"主人战力+2，命中+1",
		
		stage1_1:"1_1",
		stage1_2:"1_2",
		stage1_3:"1_3",
		stage1_4:"1_4",
		stage1_5:"1_5",
		stage2_1:"2_1",
		stage2_1Explain:"魔主得到第六个怪物时，玩家立刻失败",
		stage2_2:"2_2",
		stage2_3:"2_3",
		stage2_4:"2_4",
		stage2_4Explain:"本关只有魔主死亡这一种胜利方式",
		stage2_5:"2_5",
		stage2_5Explain:"本关只有翻完怪物牌堆，并达成分数这一种胜利方式",
		
		placeShuiyuegong:"水月宫",
		placeYinlongku:"隐龙窟",
		placeJingcheng:"京城",
		placeSuoyaota:"锁妖塔",
		placeMiaojiang:"苗疆",
		placeShushan:"蜀山",
		placeMojie:"魔界",
		
		
		
		
		
		
}